name: Create Unity Package

on: push

jobs:
  create:
    name: Generate the Unity package file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Assets/BigfootDS/BigfootUnityUtilities.meta" > metaList
        find Assets/BigfootDS/BigfootUnityUtilities/ -name \*.meta >> metaList

    - run: mkdir legacyPackage

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'legacyPackage/${{ github.event.repository.name }}_j${{ github.job }}_r${{ github.run_id }}_n${{ github.run_number }}.unitypackage'
        include-files: metaList
    - uses: actions/upload-artifact@master
      with:
        path: legacyPackage
        name: legacyPackage