name: Create Unity Package

on: push

jobs:
  create:
    name: Generate the Unity package file
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as env variable
      run: echo "::set-env name=NOW::$(date +'%Y%m%d')"
    - name: Echo $NOW 
      run: echo $NOW
    - name: Set current date as Github Actions env variable 
      env: 
        NOW: ${{ $(date +'%Y%m%d') }}
    - uses: actions/checkout@v2
    - run: |
        echo "Assets/BigfootDS/BigfootUnityUtilities.meta" > metaList
        find Assets/BigfootDS/BigfootUnityUtilities/ -name \*.meta >> metaList

    - run: mkdir legacyPackage

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'legacyPackage/${{ github.event.repository.name }}_r${{ $NOW }}_n${{ github.run_number }}.unitypackage'
        include-files: metaList
    - uses: actions/upload-artifact@master
      with:
        path: legacyPackage
        name: ${{ github.event.repository.name }}_r${{ $NOW }}_n${{ github.run_number }}Package